---
title: "Hw 4"
output: html_document
date: '2023-01-30'
---

```{r setup, include=FALSE}

library(dplyr)
library(tidyr)
library(ggplot2)
library(ggfortify)

#Import both data files, call them "cucumberdamage" and "flowercounts". 

cucumberdamage <- read.csv("lecture3_cucumberdamage.csv")
flowercounts <- read.csv("lecture3_flowercounts.csv")

cucumberdamage$plant<-as.factor(cucumberdamage$plant)
flowercounts$plant<-as.factor(flowercounts$plant)
```

```{r}
#Run this line of code after you've imported them:
#flowercounts$plant <- as.factor(flowercounts$plant) #treats each plant as level 

#2.Determine the total number (sum) of male and female flowers combined on each plant (i.e., total number of flowers, males + females).

flowercounts %>%
  group_by(plant) %>%
  summarise(across(c(M,F), sum)) -> df
df<-df %>% mutate(flowers=M+F)
df<-select(df,-M,-F)
df

#3. Join the total flower number count with the cucumberdamage dataframe (look at "Combine Tables" on the second page of the dplyr cheat sheet)
#left join data set b joins a 
cucumberdamage
combdamage<-full_join(cucumberdamage,df)
combdamage

```

```{r}
#4. Use a t-test to determine if the hand-pollination treatment affects flower number. In your annotation, explain how you interpret the result of the t-test (in your own words)
t.test(combdamage$flowers~combdamage$pollination)
```

```{r}
#5.Make a figure in ggplot depicting flower number and pollination treatment (make it look pretty given the tricks you learned last time).

graph<-ggplot(combdamage,aes(x = pollination,y=flowers)) + geom_boxplot()+ scale_x_discrete(limits=c("HP","NP"))+ theme_bw()
graph

```

```{r}
#6. On each plant, the lengths of 3 leaves were measured (leaf1length, leaf2length, leaf3length in the cucumberdamage dataframe). First, use dplyr to calculate mean leaf length of each plant. Then, test the hypothesis that hand-pollination decreases leaf size.

combdamage %>% group_by(plant) %>% 
  mutate(leaf_mean = mean(c(leaf1length,leaf2length,leaf3length),na.rm=T)) -> combdamage
t.test(combdamage$leaf_mean~combdamage$pollination)

```

```{r}
#7 Make a ggplot illustrating the results of leaf length vs hand polliantion.
graph<-ggplot(combdamage,aes(x = pollination,y=leaf_mean)) + geom_boxplot()+ scale_x_discrete(limits=c("HP","NP"))+ theme_bw()
graph
```

```{r}
#8. Be sure to include code and annotations for the next class's assigned readings in the file, and upload to Canvas before the start of the next class. Be sure to complete your peer review by then too. 

plant_gr<-read.csv("plant.growth.rate.csv")
ggplot(plant_gr,
  aes(x = soil.moisture.content, y = plant.growth.rate)) +
  geom_point() +
  ylab("Plant Growth Rate (mm/week)") +
  theme_bw()

model_pgr <- lm(plant.growth.rate ~ soil.moisture.content,
data = plant_gr) 
autoplot(model_pgr, smooth.colour = NA)
anova(model_pgr)
summary(model_pgr)

ggplot(plant_gr, aes(x = soil.moisture.content, 
y = plant.growth.rate)) +
geom_point() + geom_smooth(method = 'lm') +
ylab("Plant Growth Rate (mm/week)") +theme_bw()

daphnia<-read.csv("Daphniagrowth.csv")

ggplot(daphnia, aes(x = parasite, y = growth.rate)) +
  geom_boxplot() +theme_bw()

ggplot(daphnia, aes(x = parasite, y = growth.rate)) +
  geom_boxplot() +theme_bw() +coord_flip()

model_grow <- lm(growth.rate ~ parasite, data = daphnia) 
autoplot(model_grow, smooth.colour = NA)
anova(model_grow)
summary(model_grow)

sumDat<-daphnia %>% group_by(parasite) %>% summarise(meanGR = mean(growth.rate))

limp<-read.csv("limpet.csv") #changed density and eggs to lowercase in file- fixed error 
glimpse(limp) 
ggplot(limp, aes(x = density, y = eggs, colour = season)) +geom_point() +
scale_color_manual(values = c(spring="green", summer="red")) +
theme_bw() 
limp.mod <- lm(eggs~density*season, data = limp) 

autoplot(limp.mod, smooth.colour=NA)
anova(limp.mod) 
summary(limp.mod)
new.x <- expand.grid(density=seq(from=8, to=45, length.out=10),
season = (limp$season))
new.y<- predict(limp.mod, newdata = new.x, interval = 'confidence')
addThese <- data.frame(new.x, new.y)
addThese<-rename(addThese, eggs = fit) 
ggplot(limp, aes(x = density, y = eggs, colour = season)) +
geom_point(size = 5) +
geom_smooth(data = addThese, aes(ymin = lwr, ymax = upr, fill = season), stat = 'identity') +
scale_colour_manual(values = c(spring="green",summer="red")) +
scale_fill_manual(values = c(spring="green",summer="red")) +
theme_bw()

```

